### ISSUE TITLE
Version changes in multi-window app

### ISSUE THREAD

**Issue by beeftornado** [treojs/treo#16]
I'm not holding this against you (or treo) as this is specifically called out in the documentation, but version changes aren't handled very well when multiple windows are open and connected to the same database. Some uncaught exceptions get thrown eventually. This is a particularly big issue for my situation, but I'll come up with some workaround. I don't expect to not have to write any glue to integrate libraries.

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Version_changes_while_a_web_app_is_open_in_another_tab

It would be really helpful though if it was handled by the library. By "handled" I don't mean make the problem go away, I'm not that demanding! It would be a huge help though to support the onblocked handler or support some kind of callback if there is a problem during the open request as shown in the doc I linked to.

``` javascript
openReq.onblocked = function(event) {
  // If some other tab is loaded with the database, then it needs to be closed
  // before we can proceed.
  alert("Please close all other tabs with this site open!");
};
```

This way I can detect and either close the other connections via cross window talking or ask the user to close the tabs (like in the example).

Oh god, I have a premonition, you're going to tell me I can write a plugin aren't you.

**Comment by alekseykulikov** [comment]
since treo@0.4.1 handles onversionchange event autmatically https://github.com/alekseykulikov/treo/commit/11f0be463b3a91036ec57ab3ae776d93c7cd85e2
