### ISSUE TITLE
One schema for different databases

### ISSUE THREAD

**Issue by whitecolor** [treojs/treo#31]
Using one schema for different DBs Isn't it possible? I tried but got unexpected (for me) behaviour. Or this is by design one schema - one db?

And second question, on a little bit other issue. I have many items each of the require to have ONE storeObject (with capability of indexing, search). So I thought to have one database for all such items, but it seems that I can not dynamicly add storeObjects to db without changig the version. Is a correct way to go with that task to create DB per each of such item with only one store?

**Comment by alekseykulikov** [comment]
1) you can reuse schema for different database just by calling `treo()` with different db name.

```js
var db1 = treo('db1', schema)
var db2 = treo('db2', schema)
```

2) This is how IndexedDB works. You can't change schema without changing version.
If you need constantly add new stores, it would be easier to simply use one, and just change key pattern. This is an example to get you main idea.

```js
var schema = treo.schema()
.version(1)
  .addStore('stores')
  .addIndex({ key: 'id' }, { unique: true })

var db = treo('mydb', schema)
var stores = db.store('stores')

stores.put('books-1', { id: 1, name: 'Book 1' })
stores.put('books-2', { id: 2, name: 'Book 1' })
stores.put('authors-1', { id: 1, name: 'Author 1' })
```

**Comment by whitecolor** [comment]
each of such stores of items may contain up to several thousand items, beside I may need to remove the whole store (all items), or replace them with another one. So an such store there may be up to one handred (so potentially up to half million items in store if to use one) is this ok can indexed db handle this?

**Comment by alekseykulikov** [comment]
IndexedDB clearly can handle the situation of 0.5m items per store.
For example, Chrome's implementation is built on top of [LevelDB](https://github.com/google/leveldb) which is just key/value store, so I guess, it emulates all data in the way I described earlier.

In your case I would test different approaches, and will share with us what works better, in the case someone will have the same issue in future.
